name: Terraform GKE Cluster Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: checkout files
        run: |
          echo "$GCS_SECRET" >> gcs-secret.json
          ls -ltr
          cat gcs-secret.json
        env:
          GCS_SECRET: ${{ secrets.GCS_SECRET }}

      # - name: Set up Google Cloud credentials
      #   uses: google-github-actions/setup-gcloud@v0.5.0
      #   with:
      #     service_account_key: ${{ secrets.GCP_SA_KEY }}
      #     project_id: ${{ secrets.GCP_PROJECT_ID }}

      # - name: Decode the service account key and authenticate
      #   run: |
      #     echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 --decode > "${HOME}/gcp-key.json"
      #     gcloud auth activate-service-account --key-file="${HOME}/gcp-key.json"

      # - name: application credentials
      #   run: export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/gcp-key.json"

      # - name: Verify Google Cloud Authentication
      #   run: gcloud auth list

      # - name: Verify list bucket
      #   run: gcloud storage buckets list --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform destroy
        run: terraform destroy -auto-approve
